showMsg("Complete los Campos y presione Grabar<br />Los Campos indicados con asterisco son Requeridos<br />","highlight-alert",false);var comboContents="",startAddress="",lat="",lon="",errs=[];$.getJSON("combosManager.php?acc=am",{ajax:"true"},function(a){comboContents=a});$("#cboProvincia_ABM").change(function(){$("#cboLocalidad_ABM").children().remove();$(this).val()?$.getJSON("combosManager.php?acc=l",{idProv:$(this).val(),ajax:"true"},function(a){loadComboContent(a,$("#cboLocalidad_ABM"))}):$("#cboLocalidad_ABM").empty().html("<option value=''>Seleccione Localidad</option>")});
var $editors=$("textarea.ckeditor");$editors.length&&$editors.each(function(){var a=$(this).attr("id");CKEDITOR.instances[a]&&CKEDITOR.remove(CKEDITOR.instances[a]);CKEDITOR.replace(a,{width:500,height:200,uiColor:"#F9F9F9"})});$(".theButton").hover(function(){$(this).addClass("ui-state-hover")},function(){$(this).removeClass("ui-state-hover")});$(".delButton").live("click",function(){$($(this).closest("tr")).fadeOut(function(){$(this).remove()});return false});
$("#btnAddAmbiente").die().live("click",function(){var a=$("<select>");loadComboContent(comboContents,a);var d=$("<input type='text' />").addClass("short"),c=$("<input type='text' />").addClass("short"),e=$("#btnAddAmbiente").removeClass("ui-state-hover");$("#roomsTable tbody").append($("<tr>").append($("<td>").attr("align","left").append($(a))).append($("<td>").append($(d))).append($("<td>").append($(c))).append($("<td>").append($(e))));$("#roomsTable tbody tr").each(function(b){var g=b%2==0?"pairRow":
"unpairRow";$aRow=$(this);$aRow.attr("id",b).attr("class",g);$aRow.children().each(function(f){$aCell=$(this);$aChild=$aCell.children();if(f==0)$aChild.attr({id:"theAmbientes_ABM["+b+"][t]",name:"theAmbientes_ABM["+b+"][t]"});else if(f==1)$aChild.attr({id:"theAmbientes_ABM["+b+"][a]",name:"theAmbientes_ABM["+b+"][a]"});else f==2&&$aChild.attr({id:"theAmbientes_ABM["+b+"][l]",name:"theAmbientes_ABM["+b+"][l]"})})});return false});$("input:text").focus(function(){$(this).val("").css({backgroundColor:"#FFFFF4"})}).blur(function(){$(this).css({backgroundColor:""})});
$("input:text.short, input:text.dec").live("keyup",function(){$(this).val($(this).val().replace(/[^0-9\.]/g,"").replace(/^\./,""))}).live("blur",function(){$(this).val($(this).val().replace(/[^0-9\.]/g,"").replace(/^\./,""))});$("input:text.ent").live("keyup",function(){$(this).val($(this).val().replace(/[^0-9]/g,""))}).blur(function(){$(this).val($(this).val().replace(/[^0-9]/g,""))});
$("div#formStep_3 .montoPubs").each(function(){$(this).val().indexOf("No Ingresado")!=-1&&$(this).css({"font-style":"italic",color:"#999"})});
$("div#formStep_3 .montoPubs").keyup(function(){var a=$(this).parents("tr").children().eq(3).children("select[name$='idEstPub]']"),d=$(this),c=d.val();if(c!=""){d.val(c.replace(/[^0-9\.]/g,"").replace(/^\./,""));a.val(1)}else{d.val("No Ingresado");d.css({"font-style":"italic",color:"#999"});a.val(7)}}).blur(function(){$this=$(this);if($this.val()==""){$this.css({"font-style":"italic",color:"#999"});$this.val("No Ingresado");$this.parents("tr").children().eq(3).children("select[name$='idEstPub]']").val(7)}else{$this.val($this.val().replace(/[^0-9\.]/g,
"").replace(/^\./,""));$this.parents("tr").children().eq(3).children("select[name$='idEstPub]']").val(1)}}).focus(function(){$(this).css({"font-style":"normal",color:""})});
$("#frmPropiedad").validate({submitHandler:function(a){var d=$(a).attr("action");$.ajax({cache:false,type:$(a).attr("method"),url:d,data:$(a).serialize()+"&txtObservaciones_ABM="+escape(CKEDITOR.instances.txtObservaciones_ABM.getData())+"&lat_ABM="+lat+"&lon_ABM="+lon,success:function(c){if(c.indexOf("<li>")>0)showMsg(c,"error-alert",true);else{showMsg(c,"succesfull-alert",false);$("#ModalDialog").dialog("destroy").remove()}if($("#searchResultsPropio").html()!=""){c=getUrlVars(d).p;var e=getUrlVars(d).o;
$.ajax({type:"POST",url:$("#frmBusquedaPropia").attr("action"),data:$("#frmBusquedaPropia").serialize()+"&p="+c+"&o="+e,success:function(b){$("#searchResultsPropio").empty().html(b)},error:function(b,g){showMsg(g+": "+b.responseText,"error-alert",true)}})}},error:function(c,e){showMsg(e+": "+c.responseText,"error-alert",true)}});$("label[generated='true']").remove();$("#jGrowl").children().trigger("jGrowl.close")},errorPlacement:function(a){a.appendTo()},onfocusout:false,focusInvalid:false,onkeyup:false,
focusCleanup:true,showErrors:function(a,d){var c=$("<ul>").css({margin:"0px",padding:"5px"});$(d).each(function(e,b){if(b.message!=""&&(errs.containsElement(b.message)===false||!$(b.element).is("select"))){errs[e]=b.message;$(b.element).is(":checkbox")&&$(b.element).parent().css({backgroundColor:"#FEF1EC",border:"1px dotted #CD0A0A"});$("<li>").text(b.message).appendTo(c)}});c.children().length>0&&showMsg(c.html(),"error-alert",true);this.defaultShowErrors()},rules:{txtNumero_ABM:{maxlength:5},chkDeAcuerdo_ABM:{required:true}},
messages:{cboTipoPropiedad_ABM:{required:"El Tipo de Propiedad es Requerido"},txtCalle_ABM:{required:"La Calle es Requerida para establecer el Domicilio"},txtNumero_ABM:{required:"El Numero de Calle es Requerido para establecer el Domicilio",maxlength:"El Numero de Calle no debe contener mas de 5 Digitos"},cboProvincia_ABM:{required:"La Provincia es Requerida para establecer el Domicilio"},cboLocalidad_ABM:{required:"La Localidad es Requerida para establecer el Domicilio"},chkDeAcuerdo_ABM:{required:"Debe Aceptar que Verifica la Direccion ingresada"}}});
$("input:text.required, #cboProvincia_ABM, #cboLocalidad_ABM").blur(function(){var a=$("select.required:not([name*='Tipo']) option:selected[value!='']").map(function(){return $(this).text()}).get();if(a.length==2){$calle=$("input:text.required:eq(0)");$num=$("input:text.required:eq(1)");if($calle.val().length>1&&$num.val().length>1){var d=$calle.val()+" "+$num.val()+", "+a[0]+", "+a[1]+", Argentina";loadCanvasMap(d,a[0],a[1])}}});
$("input:checkbox.accept").click(function(){$chkBox=$(this);if($chkBox.hasClass("error")){$chkBox.parent().css({backgroundColor:"",border:"none"});$("#jGrowl").children().trigger("jGrowl.close")}$chkBox.hasClass("valid")&&$chkBox.parent().css({backgroundColor:"#FEF1EC",border:"1px dotted #CD0A0A"})});var startProvLoc=$("select.required:not([name*='Tipo']) option:selected[value!='']").map(function(){return $(this).text()}).get(),startStrtNum=$("input:text.required").map(function(){return $(this).val()}).get();
if(startProvLoc.length==2&&startStrtNum[0].length>0&&startStrtNum[1].length>0){startAddress=startStrtNum[0]+" "+startStrtNum[1]+", "+startProvLoc[0]+", "+startProvLoc[1]+", Argentina";loadCanvasMap(startAddress,startProvLoc[0],startProvLoc[1])}
function loadCanvasMap(a,d,c){$("#canvasMap").empty();var e=new google.maps.Map($("#canvasMap").get(0),{mapTypeId:google.maps.MapTypeId.ROADMAP,zoom:15,backgroundColor:"#FDFDE8"}),b=new google.maps.Geocoder,g=new google.maps.InfoWindow;b&&b.geocode({address:a},function(f,i){if(i==google.maps.GeocoderStatus.OK){e.setCenter(f[0].geometry.location);lat=f[0].geometry.location.lat();lon=f[0].geometry.location.lng();var h=new google.maps.Marker({icon:"../../css/images/markers/mark4.png",map:e,position:f[0].geometry.location});
$("input:text.required:eq(0)").val(f[0].address_components[1].long_name);$("input:text.required:eq(1)").val(f[0].address_components[0].long_name);g.setContent('<span style="font-size:9px;">'+f[0].address_components[1].long_name+" "+f[0].address_components[0].long_name+", "+c+"<br />&middot; "+d+" &middot; Argentina</span>");g.open(e,h);google.maps.event.addListener(h,"click",function(){g.open(e,h)})}else showMsg("La Direcci&oacute;n no se pudo resolver<br />Error de la API de Google Maps: "+i,"error-alert",
true)})};