$.maxZIndex=$.fn.maxZIndex=function(d){var c={inc:10,group:"*"};$.extend(c,d);var a=0;$(c.group).each(function(){var e=parseInt($(this).css("z-index"));a=e>a?e:a});if(!this.jquery)return a;return this.each(function(){a+=c.inc;$(this).css("z-index",a)})};jQuery.fn.center=function(){var d=$(window);this.css("position","absolute");this.css("top",(d.height()-this.height())/2+d.scrollTop()+"px");this.css("left",(d.width()-this.width())/2+d.scrollLeft()+"px");return this};
jQuery.fn.toggleText=function(d,c){return this.html(this.html().replace(RegExp("("+d+"|"+c+")"),function(a){return a==d?c:d}))};
$(document).ready(function(){$("#mainLoader").hide().bind("ajaxStart",function(){var a=getBrowserWindowHeightAndWidth();$(this).show();$(this).css("top",parseInt((a.height-$(this).outerHeight())/2-20)+"px")}).bind("ajaxStop",function(){$(this).fadeOut(500)});$("#tabs").tabs({disabled:[4],spinner:"<em>Cargando&#8230;</em>",ajaxOptions:{error:function(a,e,b,c){$(c.hash).html("<p align='center'><img src='../../css/images/black/404html.png' /></p>")}}});$.support.opacity||$("#tabs > ul > li").each(function(a){a<
4&&$(this).removeClass("ui-state-disabled")});SexyLightbox.initialize({find:"lb",imagesdir:"../../css/images",OverlayStyles:{"background-color":"#000000",opacity:0.8}});$("#loGoff").hover(function(){$(this).addClass("ui-state-hover")},function(){$(this).removeClass("ui-state-hover")}).tooltip({track:!0,delay:500,showURL:!1,fade:200});$(".adv:eq(1)").hover(function(){$(this).attr("src","../../css/images/gen/p-jq.png")},function(){$(this).attr("src","../../css/images/gen/p-jq-off.png")});$(".adv:eq(0)").hover(function(){$(this).attr("src",
"../../css/images/gen/p-w3c.png")},function(){$(this).attr("src","../../css/images/gen/p-w3c-off.png")});$(".orderLink, .pagLink").live("click",function(a){var e=$(this).attr("href"),b="?";e.indexOf("?")>0&&(b="&");e+=b+Math.floor(Math.random()*1.111111111111111E19);var b="#"+getUrlVars(e).idf,c="#"+getUrlVars(e).idr;$.ajax({type:"POST",url:e,data:$(this).parents($("#tabs")).children("div.searchForm").children(b).serialize(),timeout:15E3,error:function(a,b){showMsg(b+": "+a.responseText,"error-alert",
!0)},success:function(a){$(c).empty().html(a)}});$(a.target).is(".orderLink")&&$(this).toggleClass("orderLinkActive").text("Ordenando..");return!1});$("#searchResultsGlobal").live("click",function(a){$("#resultadosGlobales > tbody > tr").each(function(){$(this).removeClass("activeRow")});if($(a.target).parent().is(".accLink")){var c=$("<div />"),a=$(a.target).parent().attr("href"),b=getUrlVars(a).tittle,d=getUrlVars(a).i;c.load(a).dialog({resizable:!1,width:970,height:590,position:"top",modal:!0,
closeOnEscape:!1,open:function(){$(".ui-dialog-titlebar-close").hide()},title:b.replace(/[_]/g," "),buttons:{Cerrar:function(){$(this).dialog("destroy").remove();$("#resultadosGlobales tr#Row_"+d).effect("highlight",{},2E3,function(){$(this).addClass("activeRow")})}}});return!1}});$("#searchResultsPropio").live("click",function(a){$("#resultadosPropios > tbody > tr").each(function(){$(this).removeClass("activeRow")});if($(a.target).parent().is(".stateLink")){var e=$(a.target).parent().attr("href"),
b=getUrlVars(e).idz,f="?";e.indexOf("?")>0&&(f="&");e+=f+Math.floor(Math.random()*1.111111111111111E19);$("#stateLoading_"+b).css("display")!="none"&&$("#stateLoading_"+b).hide();$.ajax({type:"GET",url:e,timeout:15E3,beforeSend:function(){$("#stateLink_"+b).hide();$("#stateLoading_"+b).show()},error:function(a,b){showMsg(b+": "+a.responseText,"error-alert",!0)},success:function(a){a=a.split(",");$("#zonaEstadoPublicacion_"+b).html(a[1]);$("#stateLoading_"+b).hide();$("#resultadosPropios tr#Row_"+
b).effect("highlight",{},2E3,function(){$(this).addClass("activeRow")});a[0].indexOf("<li>")==-1?showMsg(a[0],"succesfull-alert",!1):showMsg(a[0],"error-alert",!0)}});return!1}else if($(a.target).parent().is(".accLink")){var h=$(a.target).parent(),f=h.attr("href"),j=h.parents($("#tabs")).children("div.searchForm").children("#frmBusquedaPropia").attr("action"),i=h.parents($("#tabs")).children("div.searchForm").children("#frmBusquedaPropia").serialize(),k=getUrlVars(f).p,l=getUrlVars(f).o,g=getUrlVars(f).acc,
b=getUrlVars(f).i,h=getUrlVars(f).tittle;i+="&p="+k+"&o="+l;g=="ve"?(a=$("<div />"),a.load(f).dialog({resizable:!1,width:970,height:590,position:"top",modal:!0,closeOnEscape:!1,open:function(){$(".ui-dialog-titlebar-close").hide()},title:h.replace(/[_]/g," "),buttons:{Cerrar:function(){$(this).dialog("destroy").remove();$("#resultadosPropios tr#Row_"+b).effect("highlight",{},2E3,function(){$(this).addClass("activeRow")})}}})):g=="de"?(e=$(a.target).parent().attr("href"),$legend=$("<p />").html("Esta seguro de Eliminar la Propiedad?<br />Esta Acci\u00f3n es irreversible!").append($("<span />").addClass("ui-icon ui-icon-alert")),
$("<div />").addClass("msgRespModal").append($legend).appendTo("body").dialog({title:"Confirmacion de Eliminacion",resizable:!1,height:150,modal:!0,closeOnEscape:!1,open:function(){$(".ui-dialog-titlebar-close").hide()},buttons:{Cancelar:function(){$(this).dialog("destroy").remove()},Eliminar:function(){$(this).dialog("destroy").remove();$.ajax({type:"GET",url:e,timeout:15E3,success:function(a){a.indexOf("No")==-1?$("#Row_"+b,$("#resultadosPropios")).fadeOut(500,function(){$(this).next().remove().end().remove();
showMsg(a,"succesfull-alert",!1);$("#resultadosPropios > tbody > tr").each(function(){$(this).removeClass("unpairRow");$(this).removeClass("pairRow");$(this).removeClass("activeRow")});$("#resultadosPropios > tbody > tr:not('.sepa'):even").addClass("pairRow");$("#resultadosPropios > tbody > tr:not('.sepa'):odd").addClass("unpairRow")}):showMsg(a,"error-alert",!0)},error:function(a,b){showMsg(b+": "+a.responseText,"error-alert",!0)}})}}})):(a=$("<div />").attr("id","ModalDialog"),a.load(f).dialog({resizable:!1,
width:970,height:590,position:"top",modal:!0,closeOnEscape:!1,open:function(){$(".ui-dialog-titlebar-close").hide()},title:h.replace(/[_]/g," "),buttons:{Cerrar:function(){g=="fo"&&$.get("./propiedadPict.php?acc=cl",function(a){a.length>0&&showMsg(a,"warning-alert",!1)});g=="ld"&&$.get("./propiedadDisp.php?acc=cl",function(a){a.length>0&&showMsg(a,"warning-alert",!1)});$(this).dialog("destroy").remove();$("#jGrowl").children().trigger("jGrowl.close");$(".imgDescription").each(function(){$(this).dialog("destroy").remove()})},
Grabar:function(){g=="ed"&&$("#frmPropiedad").submit();g=="ld"&&c(j,i);g=="fo"&&d(j,i);return!1}}}));return!1}});$("#btnAddAmbiente").live("click",function(){var a=$("<select>");loadComboContent(comboContents,a);var c=$("<input type='text' />").addClass("short"),b=$("<input type='text' />").addClass("short"),d=$("#btnAddAmbiente").removeClass("ui-state-hover");$("#roomsTable tbody").append($("<tr>").append($("<td>").attr("align","left").append($(a))).append($("<td>").append($(c))).append($("<td>").append($(b))).append($("<td>").append($(d))));
$("#roomsTable tbody tr").each(function(a){var b=a%2==0?"pairRow":"unpairRow";$aRow=$(this);$aRow.attr("id",a).attr("class",b);$aRow.children().each(function(b){$aCell=$(this);$aChild=$aCell.children();b==0?$aChild.attr({id:"theAmbientes_ABM["+a+"][t]",name:"theAmbientes_ABM["+a+"][t]"}):b==1?$aChild.attr({id:"theAmbientes_ABM["+a+"][a]",name:"theAmbientes_ABM["+a+"][a]"}):b==2&&$aChild.attr({id:"theAmbientes_ABM["+a+"][l]",name:"theAmbientes_ABM["+a+"][l]"})})});return!1});var d=function(a,c){var b=
$("#gallery").sortable("serialize"),d=$("#gallery").children("li").length;if(d>18)return b=parseInt(d,10)-18,showMsg('<ul style="margin:0px;padding:0px;"><li>S\u00f3lo se permiten hasta 18 Im\u00e1genes<br />Elimine '+b+" y vuelva a Grabar</li></ul>","error-alert",!0),!1;$.ajax({url:"./propiedadPict.php?acc=re",type:"POST",data:b,success:function(b){b.indexOf("<li>")==-1?(showMsg(b,"succesfull-alert",!1),$("#searchResultsPropio").html()!=""&&$.ajax({type:"POST",url:a,data:c,success:function(a){$("#searchResultsPropio").empty().html(a)},
error:function(a,b){showMsg(b+": "+a.responseText,"error-alert",!0)}}),$("#ModalDialog").dialog("destroy").remove(),$(".imgDescription").each(function(){$(this).dialog("destroy").remove()})):showMsg(b,"error-alert",!0)},error:function(a,b){showMsg(b+": "+a.responseText,"error-alert",!0)}})},c=function(a,c){cont>0?$.ajax({type:"GET",url:"./propiedadDisp.php?acc=re",success:function(b){b.indexOf("<li>")==-1?(showMsg(b,"succesfull-alert",!1),$("#searchResultsPropio").html()!=""&&$.ajax({type:"POST",
url:a,data:c,success:function(a){$("#searchResultsPropio").empty().html(a)},error:function(a,b){showMsg(b+": "+a.responseText,"error-alert",!0)}}),$("#ModalDialog").dialog("destroy").remove()):showMsg(b,"error-alert",!0)},error:function(a,c){showMsg(c+": "+a.responseText,"error-alert",!0)}}):showMsg('<ul style="margin:0px; padding:5px;"><li>Para Grabar debe Agregar y/o Quitar una Reserva</li></ul>',"error-alert",!0)}});function showMsg(d,c,a){$.jGrowl(d,{theme:c,sticky:a})}
function getBrowserWindowHeightAndWidth(){var d=0,c=0;if(typeof window.innerWidth=="number")d=window.innerHeight,c=window.innerWidth;else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight))d=document.documentElement.clientHeight,c=document.documentElement.clientWidth;else if(document.body&&(document.body.clientWidth||document.body.clientHeight))d=document.body.clientHeight,c=document.body.clientWidth;return{width:parseInt(c),height:parseInt(d)}}
function getUrlVars(d){var c={};d.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(a,d,b){c[d]=b});return c}
function changePaginatorPage(d,c){$("#mainLoader").show();var a=$("#comboPag").val(),e=getUrlVars(d).idr;d+="&p="+a;c?$.ajax({type:"GET",url:d,timeout:5E3,error:function(a,c){showMsg(c+": "+a.responseText,"error-alert",!0)},success:function(a){$("#"+e).empty().html(a);$("#mainLoader").hide()}}):(a=getUrlVars(d).idf,$.ajax({type:"POST",url:d,data:$("#"+a).serialize(),timeout:5E3,error:function(a,c){showMsg(c+": "+a.responseText,"error-alert",!0)},success:function(a){$("#"+e).empty().html(a);$("#mainLoader").hide()}}))}
function removeJsCssFile(d,c){for(var a=c=="js"?"src":c=="css"?"href":"none",e=document.getElementsByTagName(c=="js"?"script":c=="css"?"link":"none"),b=e.length;b>=0;b--)e[b]&&e[b].getAttribute(a)!=null&&e[b].getAttribute(a).indexOf(d)!=-1&&e[b].parentNode.removeChild(e[b])}function loadComboContent(d,c){$.each(d,function(a,d){$("<option>").attr("value",d.id).text(d.nombre).appendTo(c)})}Array.prototype.indexOf=function(d){for(var c=0;c<this.length;c++)if(this[c]==d)return c;return!1};
Array.prototype.containsElement=function(d){for(var c=0;c<this.length;c++)if(this[c]==d)return!0;return!1};